# Generated by Django 5.1.7 on 2025-03-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Truenewsapp', '0002_news_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='Фото новости'),
        ),
    ]
